Repository sumte-app/sumte-server, pull requests merged in 2025-08, with the labels that each got.

#41 [FEAT] 내 예약 목록 조회 API
  src/main/java/com/sumte/SumteApplication.java
  src/main/java/com/sumte/payment/repository/PaymentRepository.java
  src/main/java/com/sumte/reservation/converter/ReservationConverter.java
  src/main/java/com/sumte/reservation/dto/ReservationResponseDTO.java
  src/main/java/com/sumte/reservation/entity/Reservation.java
  src/main/java/com/sumte/reservation/repository/ReservationRepository.java
  src/main/java/com/sumte/reservation/scheduler/ReservationStatusScheduler.java
  src/main/java/com/sumte/reservation/service/ReservationService.java
  src/main/java/com/sumte/reservation/service/ReservationServiceImpl.java
  src/main/java/com/sumte/review/repository/ReviewRepository.java
Labels: ✨ feature

#49 [FIX] 배포 상황 속 S3 환경변수 주입 실패 해결, 디스코드 배포 알림 로직 구현
  .github/workflows/main_cd_workflow.yml
Labels: 🔨 fix

#42 [FEAT] id기반 조회 (#38)
  src/main/java/com/sumte/guesthouse/controller/GuesthouseController.java
  src/main/java/com/sumte/guesthouse/converter/GuesthouseConverter.java
  src/main/java/com/sumte/guesthouse/dto/GuesthouseResponseDTO.java
  src/main/java/com/sumte/guesthouse/repository/GuesthouseOptionServicesRepository.java
  src/main/java/com/sumte/guesthouse/repository/GuesthouseTargetAudienceRepository.java
  src/main/java/com/sumte/guesthouse/service/GuesthouseCommandServiceImpl.java
  src/main/java/com/sumte/guesthouse/service/GuesthouseQueryService.java
  src/main/java/com/sumte/guesthouse/service/GuesthouseQueryServiceImpl.java
  src/main/java/com/sumte/room/controller/RoomController.java
  src/main/java/com/sumte/room/dto/RoomRequestDTO.java
  src/main/java/com/sumte/room/dto/RoomResponseDTO.java
  src/main/java/com/sumte/room/entity/Room.java
  src/main/java/com/sumte/room/service/RoomCommandServiceImpl.java
  src/main/java/com/sumte/room/service/RoomQueryService.java
  src/main/java/com/sumte/room/service/RoomQueryServiceImpl.java
Labels: ✨ feature

#19 [FEAT] 홈 화면 게스트하우스 목록 조회
  src/main/java/com/sumte/guesthouse/controller/GuesthouseController.java
  src/main/java/com/sumte/guesthouse/converter/GuesthouseConverter.java
  src/main/java/com/sumte/guesthouse/dto/GuesthouseResponseDTO.java
  src/main/java/com/sumte/guesthouse/entity/Guesthouse.java
  src/main/java/com/sumte/guesthouse/repository/GuesthouseRepository.java
  src/main/java/com/sumte/guesthouse/service/GuesthouseCommandService.java
  src/main/java/com/sumte/guesthouse/service/GuesthouseCommandServiceImpl.java
  src/main/java/com/sumte/guesthouse/service/GuesthouseQueryService.java
  src/main/java/com/sumte/guesthouse/service/GuesthouseQueryServiceImpl.java
  src/main/java/com/sumte/review/repository/ReviewRepository.java
  src/main/java/com/sumte/room/controller/RoomController.java
  src/main/java/com/sumte/room/converter/RoomConverter.java
  src/main/java/com/sumte/room/dto/RoomResponseDTO.java
  src/main/java/com/sumte/room/repository/RoomRepository.java
  src/main/java/com/sumte/room/service/RoomQueryService.java
  src/main/java/com/sumte/room/service/RoomQueryServiceImpl.java
Labels: ✨ feature

#51 [FEAT] 이미지 저장·조회·교체 API 구현 이미지 다중 처리 로직 구현 (#50)
  src/main/java/com/sumte/apiPayload/code/error/ImageErrorCode.java
  src/main/java/com/sumte/guesthouse/controller/GuesthouseController.java
  src/main/java/com/sumte/guesthouse/controller/OptionServiceController.java
  src/main/java/com/sumte/guesthouse/controller/TargetAudienceController.java
  src/main/java/com/sumte/guesthouse/converter/GuesthouseConverter.java
  src/main/java/com/sumte/guesthouse/dto/GuesthouseDetailDTO.java
  src/main/java/com/sumte/guesthouse/dto/GuesthousePreviewDTO.java
  src/main/java/com/sumte/guesthouse/dto/GuesthouseResponseDTO.java
  src/main/java/com/sumte/guesthouse/entity/Guesthouse.java
  src/main/java/com/sumte/guesthouse/service/GuesthouseCommandServiceImpl.java
  src/main/java/com/sumte/guesthouse/service/GuesthouseQueryService.java
  src/main/java/com/sumte/guesthouse/service/GuesthouseQueryServiceImpl.java
  src/main/java/com/sumte/image/controller/ImageController.java
  src/main/java/com/sumte/image/controller/S3FileUploadController.java
  src/main/java/com/sumte/image/dto/ImageRequestDTO.java
  src/main/java/com/sumte/image/dto/ImageResponseDTO.java
  src/main/java/com/sumte/image/dto/ReplaceImageRequestDTO.java
  src/main/java/com/sumte/image/dto/S3UploadInfoDTO.java
  src/main/java/com/sumte/image/repository/ImageRepository.java
  src/main/java/com/sumte/image/service/ImageService.java
  src/main/java/com/sumte/image/service/S3FileUploadService.java
  src/main/java/com/sumte/reservation/controller/ReservationController.java
  src/main/java/com/sumte/reservation/converter/ReservationConverter.java
  src/main/java/com/sumte/reservation/service/ReservationServiceImpl.java
  src/main/java/com/sumte/review/controller/ReviewController.java
  src/main/java/com/sumte/review/converter/ReviewConverter.java
  src/main/java/com/sumte/review/dto/ReviewRequestDto.java
  src/main/java/com/sumte/review/dto/ReviewResponseDto.java
  src/main/java/com/sumte/review/dto/ReviewSearchDto.java
  src/main/java/com/sumte/review/entity/Review.java
  src/main/java/com/sumte/review/service/ReviewService.java
  src/main/java/com/sumte/room/controller/RoomController.java
  src/main/java/com/sumte/room/converter/RoomConverter.java
  src/main/java/com/sumte/room/dto/RoomRequestDTO.java
  src/main/java/com/sumte/room/dto/RoomResponseDTO.java
  src/main/java/com/sumte/room/entity/Room.java
  src/main/java/com/sumte/room/service/RoomCommandServiceImpl.java
  src/main/java/com/sumte/room/service/RoomQueryServiceImpl.java
  src/main/java/com/sumte/security/controller/SignInController.java
  src/main/java/com/sumte/security/controller/SignUpController.java
  src/main/resources/application-prod.yml
Labels: ✨ feature

#47 [FEAT] 카카오페이 연동 구현
  build.gradle
  src/main/java/com/sumte/payment/controller/PaymentController.java
  src/main/java/com/sumte/payment/converter/PaymentConverter.java
  src/main/java/com/sumte/payment/dto/KakaoPayApproveRequestDTO.java
  src/main/java/com/sumte/payment/dto/KakaoPayApproveResponseDTO.java
  src/main/java/com/sumte/payment/dto/KakaoPayReadyRequestDTO.java
  src/main/java/com/sumte/payment/dto/KakaoPayReadyResponseDTO.java
  src/main/java/com/sumte/payment/dto/PaymentRequestDTO.java
  src/main/java/com/sumte/payment/entity/Payment.java
  src/main/java/com/sumte/payment/kakaopay/KakaoPayClient.java
  src/main/java/com/sumte/payment/kakaopay/WebClientConfig.java
  src/main/java/com/sumte/payment/service/PaymentService.java
  src/main/java/com/sumte/payment/service/PaymentServiceImpl.java
  src/main/java/com/sumte/reservation/controller/ReservationController.java
  src/main/java/com/sumte/reservation/service/ReservationService.java
  src/main/java/com/sumte/reservation/service/ReservationServiceImpl.java
  src/main/resources/application-prod.yml
Labels: ✨ feature

#57 [fix/#46] getDetails 에서 getPricipal로 수정
  .github/workflows/main_cd_workflow.yml
  src/main/java/com/sumte/payment/controller/PaymentController.java
  src/main/java/com/sumte/payment/converter/PaymentConverter.java
  src/main/java/com/sumte/payment/dto/PaymentRequestDTO.java
  src/main/java/com/sumte/payment/dto/PaymentResponseDTO.java
  src/main/java/com/sumte/payment/service/PaymentService.java
  src/main/java/com/sumte/payment/service/PaymentServiceImpl.java
  src/main/java/com/sumte/reservation/service/ReservationServiceImpl.java
  src/main/resources/application-prod.yml
Labels: 🐞 bug

#64 [fix/#63] 예약 response 수정
  src/main/java/com/sumte/reservation/controller/ReservationController.java
Labels: 🔨 fix

#76 [FEAT] 예약 불가한 날짜 반환 API(#73)
  src/main/java/com/sumte/payment/controller/RefundController.java
  src/main/java/com/sumte/payment/converter/PaymentConverter.java
  src/main/java/com/sumte/payment/dto/KakaoPayReadyResponseDTO.java
  src/main/java/com/sumte/payment/dto/PaymentResponseDTO.java
  src/main/java/com/sumte/payment/service/PaymentServiceImpl.java
  src/main/java/com/sumte/reservation/repository/ReservationRepository.java
  src/main/java/com/sumte/room/controller/RoomController.java
  src/main/java/com/sumte/room/repository/RoomRepository.java
  src/main/java/com/sumte/room/service/RoomQueryService.java
  src/main/java/com/sumte/room/service/RoomQueryServiceImpl.java
Labels: ✨ feature

#82 [FIX] 게하 상세조회 반환 필드 추가 (#81)
  src/main/java/com/sumte/guesthouse/dto/GuesthouseDetailDTO.java
  src/main/java/com/sumte/guesthouse/service/GuesthouseQueryServiceImpl.java
Labels: 🔨 fix

#84 [FIX] 결제 리다이렉션 로그 추가(#79)
  src/main/java/com/sumte/payment/controller/KakaoRedirectController.java
  src/main/java/com/sumte/reservation/dto/ReservationResponseDTO.java
Labels: 🔧 chore

#87 [FEAT] 임의의 결제 승인 api 추가
  src/main/java/com/sumte/payment/controller/KakaoRedirectController.java
  src/main/java/com/sumte/payment/controller/PaymentController.java
  src/main/java/com/sumte/payment/service/PaymentService.java
  src/main/java/com/sumte/payment/service/PaymentServiceImpl.java
  src/main/java/com/sumte/reservation/converter/ReservationConverter.java
  src/main/java/com/sumte/reservation/dto/ReservationResponseDTO.java
  src/main/java/com/sumte/review/dto/ReviewRequestDto.java
Labels: ✨ feature, 🔨 fix

#86 [FEAT] 리뷰 등록 및 수정에서 contents 필드 null 입력 가능
  src/main/java/com/sumte/review/dto/ReviewRequestDto.java
Labels: ✨ feature

#90 [BUG] 게스트 하우스 삭제 에러 해결 (#88)
  src/main/java/com/sumte/guesthouse/service/GuesthouseCommandServiceImpl.java
  src/main/java/com/sumte/user/repository/FavoriteRepository.java
Labels: 🐞 bug

#97 [FIX] maxPeople 반환하도록 수정 (#96)
  src/main/java/com/sumte/guesthouse/dto/GuesthouseDetailDTO.java
  src/main/java/com/sumte/guesthouse/service/GuesthouseQueryServiceImpl.java
Labels: 🔨 fix
