Repository sumte-app/sumte-server, pull requests merged in 2025-07, with the labels that each got.

#14 [CHORE] QueryDSL 설정 (#13)
  build.gradle
  src/main/java/com/sumte/config/QueryDSLConfig.java
Labels: 🔧 chore

#8 [FEAT] 리뷰&찜 등록/수정/삭제/조회 API 구현
  src/main/java/com/sumte/apiPayload/code/error/FavoriteErrorCode.java
  src/main/java/com/sumte/apiPayload/code/error/ReviewErrorCode.java
  src/main/java/com/sumte/review/controller/ReviewController.java
  src/main/java/com/sumte/review/converter/ReviewConverter.java
  src/main/java/com/sumte/review/dto/ReviewRequestDto.java
  src/main/java/com/sumte/review/dto/ReviewResponseDto.java
  src/main/java/com/sumte/review/dto/ReviewSearchDto.java
  src/main/java/com/sumte/review/entity/Review.java
  src/main/java/com/sumte/review/repository/ReviewRepository.java
  src/main/java/com/sumte/review/service/ReviewService.java
  src/main/java/com/sumte/user/controller/FavoriteController.java
  src/main/java/com/sumte/user/dto/FavoriteResponseDto.java
  src/main/java/com/sumte/user/entity/Favorite.java
  src/main/java/com/sumte/user/repository/FavoriteRepository.java
  src/main/java/com/sumte/user/service/FavoriteService.java
Labels: ✨ feature

#27 [CICD] 25.07.08 develop 브랜치 배포
  .github/workflows/main_cd_workflow.yml
Labels: 🖧 cicd

#29 [CICD] 25.07.08 develop 브랜치 배포
  .github/workflows/main_cd_workflow.yml
Labels: 🖧 cicd

#33 [CICD] 25.07.08 develop 브랜치 배포
  .github/workflows/main_cd_workflow.yml
Labels: 🖧 cicd

#21 [FEAT] 필터링 조회 및 서비스 전체 조회(#18)
  .gitignore
  build.gradle
  src/main/java/com/sumte/guesthouse/controller/GuesthouseController.java
  src/main/java/com/sumte/guesthouse/controller/OptionServiceController.java
  src/main/java/com/sumte/guesthouse/controller/TargetAudienceController.java
  src/main/java/com/sumte/guesthouse/converter/OptionServiceConverter.java
  src/main/java/com/sumte/guesthouse/converter/TargetAudienceConverter.java
  src/main/java/com/sumte/guesthouse/dto/GuesthousePreviewDTO.java
  src/main/java/com/sumte/guesthouse/dto/GuesthouseSearchRequestDTO.java
  src/main/java/com/sumte/guesthouse/dto/OptionResponseDTO.java
  src/main/java/com/sumte/guesthouse/entity/OptionServices.java
  src/main/java/com/sumte/guesthouse/repository/GuesthouseRepositoryCustom.java
  src/main/java/com/sumte/guesthouse/repository/GuesthouseRepositoryImpl.java
  src/main/java/com/sumte/guesthouse/repository/OptionServicesRepository.java
  src/main/java/com/sumte/guesthouse/repository/TargetAudienceRepository.java
  src/main/java/com/sumte/guesthouse/service/GuesthouseQueryService.java
  src/main/java/com/sumte/guesthouse/service/GuesthouseQueryServiceImpl.java
  src/main/java/com/sumte/guesthouse/service/OptionQueryService.java
  src/main/java/com/sumte/guesthouse/service/TargetQeuryService.java
  src/main/java/com/sumte/room/controller/RoomController.java
  src/main/java/com/sumte/room/converter/RoomConverter.java
  src/main/java/com/sumte/room/dto/RoomRequestDTO.java
  src/main/java/com/sumte/room/dto/RoomResponseDTO.java
  src/main/java/com/sumte/room/entity/Room.java
  src/main/java/com/sumte/room/service/RoomCommandService.java
  src/main/java/com/sumte/room/service/RoomCommandServiceImpl.java
Labels: ✨ feature

#43 [CICD] 25.07.24 develop 브랜치 배포
  .gitignore
  build.gradle
  src/main/java/com/sumte/apiPayload/code/error/CommonErrorCode.java
  src/main/java/com/sumte/apiPayload/code/error/PaymentErrorCode.java
  src/main/java/com/sumte/apiPayload/code/error/SecurityErrorCode.java
  src/main/java/com/sumte/guesthouse/controller/GuesthouseController.java
  src/main/java/com/sumte/guesthouse/controller/OptionServiceController.java
  src/main/java/com/sumte/guesthouse/controller/TargetAudienceController.java
  src/main/java/com/sumte/guesthouse/converter/OptionServiceConverter.java
  src/main/java/com/sumte/guesthouse/converter/TargetAudienceConverter.java
  src/main/java/com/sumte/guesthouse/dto/GuesthousePreviewDTO.java
  src/main/java/com/sumte/guesthouse/dto/GuesthouseSearchRequestDTO.java
  src/main/java/com/sumte/guesthouse/dto/OptionResponseDTO.java
  src/main/java/com/sumte/guesthouse/entity/OptionServices.java
  src/main/java/com/sumte/guesthouse/repository/GuesthouseRepositoryCustom.java
  src/main/java/com/sumte/guesthouse/repository/GuesthouseRepositoryImpl.java
  src/main/java/com/sumte/guesthouse/repository/OptionServicesRepository.java
  src/main/java/com/sumte/guesthouse/repository/TargetAudienceRepository.java
  src/main/java/com/sumte/guesthouse/service/GuesthouseQueryService.java
  src/main/java/com/sumte/guesthouse/service/GuesthouseQueryServiceImpl.java
  src/main/java/com/sumte/guesthouse/service/OptionQueryService.java
  src/main/java/com/sumte/guesthouse/service/TargetQeuryService.java
  src/main/java/com/sumte/payment/controller/PaymentController.java
  src/main/java/com/sumte/payment/controller/RefundController.java
  src/main/java/com/sumte/payment/converter/PaymentConverter.java
  src/main/java/com/sumte/payment/converter/RefundConverter.java
  src/main/java/com/sumte/payment/dto/PaymentRequestDTO.java
  src/main/java/com/sumte/payment/dto/PaymentResponseDTO.java
  src/main/java/com/sumte/payment/dto/RefundRequestDTO.java
  src/main/java/com/sumte/payment/entity/Payment.java
  src/main/java/com/sumte/payment/entity/PaymentStatus.java
  src/main/java/com/sumte/payment/entity/Refund.java
  src/main/java/com/sumte/payment/repository/PaymentRepository.java
  src/main/java/com/sumte/payment/repository/RefundRepository.java
  src/main/java/com/sumte/payment/service/PaymentService.java
  src/main/java/com/sumte/payment/service/PaymentServiceImpl.java
  src/main/java/com/sumte/payment/service/PaymentTransactionHelper.java
  src/main/java/com/sumte/payment/service/RefundService.java
  src/main/java/com/sumte/payment/service/RefundServiceImpl.java
  src/main/java/com/sumte/room/controller/RoomController.java
  src/main/java/com/sumte/room/converter/RoomConverter.java
  src/main/java/com/sumte/room/dto/RoomRequestDTO.java
  src/main/java/com/sumte/room/dto/RoomResponseDTO.java
  src/main/java/com/sumte/room/entity/Room.java
  src/main/java/com/sumte/room/service/RoomCommandService.java
  src/main/java/com/sumte/room/service/RoomCommandServiceImpl.java
  src/main/java/com/sumte/security/controller/SignUpController.java
  src/main/java/com/sumte/security/service/SignUpService.java
  src/main/java/com/sumte/user/controller/UserController.java
  src/main/java/com/sumte/user/dto/UserNicknameUpdateRequest.java
  src/main/java/com/sumte/user/entity/User.java
  src/main/java/com/sumte/user/repository/UserRepository.java
  src/main/java/com/sumte/user/service/UserService.java
Labels: 🖧 cicd

#44 [CICD] 25.07.24 develop 브랜치 배포
  src/main/java/com/sumte/image/service/S3FileUploadService.java
Labels: 🖧 cicd

#45 [CICD] 25.07.24 develop 브랜치 배포
  src/main/java/com/sumte/image/service/S3FileUploadService.java
Labels: 🖧 cicd
